# code: language=yaml
---
obs_path: "/opt/metrics"
obs_config_alloy: "config.alloy"

obs_server_proto: "http"
obs_server_fqdn: "srv-obs.internal.net"
obs_server_port: "9009"

local_directories:
  - "{{ obs_path }}"
  - /mnt/docker_shared

## --> Images
## Images internal
img_alloy: "{{ docker.insecure_registries.r01.host }}:{{ docker.insecure_registries.r01.port }}/alloy:latest"

## ...or Images Public
# img_alloy: "grafana/alloy:latest"
## <-- Images