# code: language=ansible

---

- name: "Configuration [all VMs]. Docker install"
  vars_files:
    - ../.vault.enc
  hosts:
    - all
  become: true
  gather_facts: true
  roles:
    - role: role_docker
      when: ansible_facts["system"] | lower == "linux"

# - name: "Configuration [all VMs]. Front"
#   vars_files:
#     - ../.vault.enc
#   hosts:
#     - front
#   become: true
#   gather_facts: true
#   roles:
#     - role: role_front
#       when: ansible_facts["system"] | lower == "linux"

# - name: "Configuration [front]"
#   vars_files:
#     - ../.vault.enc
#   hosts:
#     - front
#   become: true
#   gather_facts: true
#   roles:
#     - role: role_front
#       when: ansible_facts["system"] | lower == "linux"

# - name: "Configuration [postgresql]"
#   vars_files:
#     - ../.vault.enc
#   hosts:
#     - postgresql
#   become: true
#   gather_facts: true
#   roles:
#     - role: role_postgresql
#       when: ansible_facts["system"] | lower == "linux"

# - name: "Configuration [observability]"
#   vars_files:
#     - ../.vault.enc
#   hosts:
#     - obs
#   become: true
#   gather_facts: true
#   roles:
#     - role: role_obs
#       when: ansible_facts["system"] | lower == "linux"
