# code: language=yaml
# playbooks/playbook_pg.yaml
---
- name: "Configuration [postgres DBs]"
  vars_files:
    - ../.vault.enc
  hosts:
    - databases
  become: true
  gather_facts: true
  roles:
    - role: role_pg
      when: ansible_facts["system"] | lower == "linux"