# code: language=ansible
# playbooks/playbook_global.yaml
---

- name: "Configuration [all VMs]. Docker install"
  vars_files:
    - ../.vault.enc
  hosts:
    - all
  become: true
  gather_facts: true
  roles:
    - role: role_docker
      when: ansible_facts["system"] | lower == "linux"
