---
all:

  children:
    front:
      hosts:
        front_001:
          ansible_host: 10.130.0.6
          primary_host: "srv-pg.internal.net"
          primary_port: 5432

    obs:
      hosts:
        obs_001:
          ansible_host: 10.130.0.21

    nexus:
      hosts:
        nexus_001:
          ansible_host: 10.130.0.16

    databases:
      hosts:
        db_pg_001:
          ansible_host: 10.130.0.29
          pgtype: "primary"
        db_pg_replica_001:
          ansible_host: 10.130.0.31
          pgtype: "standby"
          primary_host: "srv-pg.internal.net"
          primary_port: 5432

